groups:
- name: django_alerts
  rules:
  # High request latency alerts
  - alert: HighRequestLatency
    expr: rate(django_http_requests_latency_including_middlewares_seconds_by_view_method_sum[5m]) / rate(django_http_requests_latency_including_middlewares_seconds_by_view_method_count[5m]) > 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High request latency on {{ $labels.instance }}"
      description: "Django application request latency is above 0.5 seconds for view {{ $labels.view }}"
  # High request rate alerts
  - alert: HighRequestRate
    expr: sum(rate(django_http_requests_total_by_method_total[5m])) by (method) > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High request rate for {{ $labels.method }} requests"
      description: "Django application is receiving more than 100 {{ $labels.method }} requests per second"
  # High error rate alerts
  - alert: HighErrorRate
    expr: rate(django_http_responses_total_by_status_total{status=~"5.*"}[5m]) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High error rate on {{ $labels.instance }}"
      description: "Django application is returning 5xx errors"
  # High database operations alerts
  - alert: DatabaseOperationsHigh
    expr: rate(django_db_execute_total[5m]) > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High database operations"
      description: "Django application is performing too many database operations"
  # High model creation alerts
  - alert: ModelDeletionsHigh
    expr: rate(django_model_deletes_total[5m]) > 50
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High model deletion rate"
      description: "Unusual number of model deletions detected"
  # High model update alerts
  - alert: ExceptionsCaught
    expr: increase(django_exceptions_total[5m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Django exceptions detected"
      description: "Application is raising exceptions"

- name: basic_monitoring
  rules:
  # Service availability alerts
  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Service {{ $labels.instance }} is down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

  # High CPU usage alerts
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: "CPU usage is above 85% for more than 5 minutes"

  # Memory alerts
  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on {{ $labels.instance }}"
      description: "Memory usage is above 85% for more than 5 minutes"

  # PostgreSQL alerts
  - alert: PostgreSQLDown
    expr: pg_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "PostgreSQL is down"
      description: "PostgreSQL instance is not accessible"

  # PostgreSQL specific alerts
  - alert: PostgreSQLHighConnections
    expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL high connection usage"
      description: "PostgreSQL instance is using more than 80% of available connections"

  # Redis alerts
  - alert: RedisDown
    expr: redis_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Redis is down"
      description: "Redis instance is not accessible"

  # Backend specific alerts
  - alert: BackendRestarting
    expr: changes(process_start_time_seconds{job="django"}[15m]) > 2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Backend restarting frequently"
      description: "Backend has restarted multiple times in the last 15 minutes"

  - alert: BackendHighOpenFiles
    expr: process_open_fds / process_max_fds * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High number of open files"
      description: "Backend is using more than 80% of available file descriptors"